# Generated by Django 4.1 on 2022-10-29 22:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='miduser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='miduser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='miduser',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='miduser',
            name='resto',
        ),
        migrations.RemoveField(
            model_name='miduser',
            name='tourguide',
        ),
        migrations.RemoveField(
            model_name='miduser',
            name='transport',
        ),
        migrations.AddField(
            model_name='miduser',
            name='role',
            field=models.CharField(default='user', max_length=8),
        ),
    ]
