# Generated by Django 4.1 on 2022-10-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_miduser_managers_remove_miduser_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MIDuser',
        ),
    ]
