# Generated by Django 4.1 on 2022-10-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=40)),
                ('transport_price', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
