# Generated by Django 4.1 on 2022-11-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('transport_name', models.CharField(max_length=50)),
                ('transport_price', models.TextField()),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
