# Generated by Django 4.1 on 2022-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_transport', '0002_transportlist_availability_transportlist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportlist',
            name='user',
        ),
        migrations.AddField(
            model_name='transportlist',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
