# Generated by Django 4.1 on 2022-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_transport', '0003_remove_transportlist_user_transportlist_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportlist',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
