# Generated by Django 4.1 on 2022-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_transport', '0005_alter_transportlist_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportlist',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
