# Generated by Django 4.1 on 2022-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_transport', '0006_alter_transportlist_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportlist',
            name='availability',
            field=models.CharField(default='Available', max_length=10),
        ),
    ]
