# Generated by Django 4.1 on 2022-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='room/'),
        ),
    ]
