# Generated by Django 4.1 on 2022-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_hotel_photo_alter_rooms_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='booking',
            field=models.BooleanField(default=False),
        ),
    ]
