# Generated by Django 4.1 on 2022-11-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_booking_rooms_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_photo',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_photo',
        ),
    ]
