# Generated by Django 4.1 on 2022-11-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_hotel_photo_remove_rooms_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='room/'),
        ),
    ]
