# Generated by Django 4.1 on 2022-12-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0002_alter_task_date_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
