# Generated by Django 4.1 on 2022-10-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0003_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
    ]
