# Generated by Django 4.1 on 2022-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0004_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
