# Generated by Django 4.1 on 2022-10-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_alter_landmark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
