# Generated by Django 4.1 on 2022-10-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_name', models.CharField(max_length=64)),
                ('reserve_from', models.TimeField()),
                ('reserve_to', models.TimeField()),
                ('reserve_seats', models.IntegerField()),
                ('reserve_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=64)),
                ('resto_address', models.CharField(max_length=128)),
                ('resto_email', models.EmailField(max_length=254)),
                ('resto_phone', models.BigIntegerField()),
                ('resto_days', models.CharField(max_length=128)),
                ('resto_open_hour', models.TimeField()),
                ('resto_close_hour', models.TimeField()),
                ('resto_description', models.TextField()),
                ('resto_photo', models.ImageField(blank=True, upload_to='')),
                ('resto_menu', models.FileField(blank=True, upload_to='')),
                ('resto_delivery', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64)),
                ('food_price', models.IntegerField()),
                ('food_stock', models.BooleanField()),
                ('food_description', models.TextField()),
                ('food_photo', models.ImageField(upload_to='')),
                ('food_resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.restaurant')),
            ],
        ),
    ]
