# Generated by Django 4.1 on 2022-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_alter_restaurant_resto_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('hours_from_hour', models.TimeField()),
                ('hours_to_hour', models.TimeField()),
            ],
            options={
                'ordering': ('hours_weekday', 'hours_from_hour'),
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='resto_close_hour',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='resto_days',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='resto_open_hour',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='hours_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('hours_weekday', 'hours_from_hour', 'hours_to_hour')},
        ),
    ]
