# Generated by Django 4.1 on 2022-10-25 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_openinghours_delete_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='resto_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False),
        ),
    ]
