# Generated by Django 4.1 on 2022-10-25 14:00

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Restaurant = apps.get_model('resto', 'Restaurant')
    for row in Restaurant.objects.all():
        row.resto_id = uuid.uuid4()
        row.save(update_fields=['resto_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_remove_restaurant_id_restaurant_resto_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
