# Generated by Django 4.1 on 2022-10-25 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0007_restaurant_id_alter_openinghours_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='resto_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
