# Generated by Django 4.1 on 2022-10-25 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_alter_restaurant_resto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='resto_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
