# Generated by Django 4.1 on 2022-10-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0009_alter_restaurant_resto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='hours_weekday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
