# Generated by Django 4.1 on 2022-10-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0010_alter_openinghours_hours_weekday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('hours_weekday', 'hours_from_hour', 'hours_to_hour', 'hours_restaurant')},
        ),
    ]
