# Generated by Django 4.1 on 2022-10-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0011_alter_openinghours_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resto/'),
        ),
    ]
