# Generated by Django 4.1 on 2022-10-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0013_alter_food_food_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='resto_menu',
        ),
    ]
