# Generated by Django 4.1 on 2022-10-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0014_remove_restaurant_resto_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={},
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='hours_weekday',
            field=models.IntegerField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')]),
        ),
    ]
