# Generated by Django 4.1 on 2022-10-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0016_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='resto_id',
        ),
    ]
